baseURL: https://shenawy.netlify.app/
languageCode: en-us
title: Ahmed Profile
theme: hugo-profile

outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - RSS

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
#  main:
  #  - identifier: blog
  #    name: Blog
  #    title: Blog posts
  #    url: /blogs
  #    weight: 1
  #  - identifier: gallery
  #    name: Gallery
  #    title: Blog posts
  #    url: /gallery
  #    weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: Ahmed Shenawy
  description: Personal Digital Corner
  # staticPath:   # The path to serve the static files from
  favicon: /fav.png

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, css or js to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of  in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: YOUR_CLOUD_NAME

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: light # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: /fav.png # Logo for the brand | default is the favicon variable
    showBrandLogo: true # Show brand logo in nav bar | default is true
    brandName: Ahmed Shenawy # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: Search
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: true
      disableCourses: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: Hi, my name is
    title: Ahmed Shenawy.
    subtitle: I have wide experience in optimizing Mobile Core Network Services and Enhancing Roaming Services
    content: With a background in mobile core network and roaming servies, I specialize in fine-tuning mobile services and ensuring top-tier performance. I'm dedicated to delivering excellence in telecommunications, actively contributing to industry standards, and staying at the forefront of technological advancements. My goal is to optimize mobile core networks and provide subscribers with seamless, high-quality services.
    image: /images/me2.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: Resume
      url: /CV Ahmed Shenawy.pdf
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/ahmedshenawy/

  # About
  about:
    enable: true
    title: About Me
    #image: /images/me.png
    content: |-
      I'm a telecommunications professional with a deep-seated passion for optimizing mobile core networks and enhancing roaming services. My educational foundation lies in computer engineering, and I've developed a keen interest in the dynamic intersection of technology and efficient network management.

      Presently, I hold the position of Senior Roaming Engineer in RMI - Rakuten Mobile International, where I actively engage in planning, deploying, and testing new mobile roaming services, including IMS services and 5G SDA products. My aspiration is to create an environment where subscribers experience top-tier services consistently.
    skills:
      enable: true
      title: "Here are some highlights of my skillset portfolio:"
      items:
        - Mobile Core Services
        - SS7 Protocol Stack
        - SIGTRAN Protocol Stack
        - Product Lifecycle Management
        - Mobile Terminal Testing & Debugging
        - QxDM, QPST and QCAT
        - Regression Testing
        - Roaming Services
        - QlikSense and Microsoft Power BI
        - Raoming TADIG & IREG

  # Experience
  experience:
    enable: true
    # title: Custom Name
    items:
      - job: Senior Raoming Engineer
        company: RMI - Rakuten Mobile International
        companyUrl: https://global.rakuten.com/corp/
        date: Oct 2023 - present
        featuredLink:
          enable: false
          url:
        content: I am currently working on a project assignment for an MNO operator in Germany to develop and launch the international roaming services.

      - job: Mobile Network Administrator
        company: Primetel
        companyUrl: https://www.primetel.com.cy/
        date: Aug 2016 - Oct 2023
        featuredLink:
          enable: false
          url:
        info:
          enable: false
          content:
        content: |
          I had the privilage to work as a Mobile Network Engineer for more than seven years. Pariticipating in many project related to the mobile core network.

          - Participated in new mobile services planning, deployment and ATP testing operations like IMS services.
          - Responsible for mobile network quality, performance metrics, KPIs and alarms for all mobile services through all network elements MSC, HLR, HSS, ATS, CSCF, SPS, MGW, UGW, MME and designing BI dashboards using QlikSense and Microsoft Power BI.
          - Expertly oversee Level 2 technical support for all mobile services (Voice, SMS, PS, IMS, Supplementary) for the subscribers inclusively (local / outbound roamers / inbound roamers) through all communication channels reported by PrimeTel CS/TS/NOC and roaming partners.
          - Responsible for mobile support internal ticketing system operations as defining areas of improvements in support processes and measuring SLA to ensure high QoS.
          - Lead mobile terminals technical operations including testing new terminals, handling mobile support issues related to terminals and coordinating with OEM companies new SW and/or new MR for new mobile services like IMS services. 
          - Operational experience on logging tools QxDM, QPST and QCAT for Qualcomm chipsets. As well as engineering mode logging for Mediatek, Spreadtrum chipsets.
          - Responsible for the TADIG operations for outbound and inbound roaming services including validation of all IREG tests (IR24/IR35/IR32/IR38/IR25), handling TADIG validation for new SIOT agreements, issuing of TCC and giving final Go to roaming commercial team for new services' launches 
          - Responsible for TAP & NRTRDE files flows in/out through DCH and roaming partners including handing TAP files technical issues related to formats.
          - Participated in IREG testing for inbound and outbound roaming services and troubleshoot any related technical issues. 
          - Operational experience of SS7, MAP and Diameter Protocols.
          - Operational experience of network management systems of difference vendors including Huawei & ZTE for Core and RAN services.
          - Participated in GSM Association groups including Interoperability Data specifications and Settlement , 5G, Technical Adaptation of Devices, Billing and Charging Evolution, Roaming in LTE , Roaming Charging Principles.

      - job: Roaming Coordinator
        company: Primetel
        companyUrl: https://www.primetel.com.cy/
        date: Jun 2014 - Aug 2016
        info:
          enable: false
        featuredLink:
          enable: false
          url:
        content: |
          I joined as a Roaming Cordinator in the pre-launch phase for the roaming services and I was one of the key persons launching it and managing the whole lifecycle of the roaming services.

          - Commercial planning of new services and platforms, including internal activities.
          - Accountable of the procurement process of acquiring new services from roaming services' vendors end-to-end.
          - Accountable of forecasting the budget and optimizing the CapEx and OpEx of the roaming services.
          - Assist in formalizing the roaming roadmap Strategy.
          - Design business cases for special inter-operator tariffs.
          - Accountable of preparing roaming regulatory reports requested by local regulator or EU BEREC.
          - Follow up and implement any new regulations for roaming retail tariffs.
          - Participate in planning and scheduling of IREG tests for all services (GSM, CAMEL, 3G & LTE) with roaming partners and internal teams.
          - Assist on reconciliation of Receivables (AR) and Payables (AP) roaming accounts with the internal accounting team.
          - Coordinate and handle any updates for the AA14/IOT/OpData document through GSM Association RAEX system.
          - Monitor TAP/RAP/NRTRDE files flow from End-to-End perspective with related internal Teams, Roaming Partners & DCH.

      - job: Roaming Engineer
        company: Etisalat Egypt
        companyUrl: https://www.etisalat.eg/StaticFiles/portal2/etisalat/index_en.html
        date: Mar 2012 - Apr 2014
        featuredLink:
          enable: false
          url:
        content: |
          I was part of the roaming revenue operations teams, mostly monitoring the daily traffic and analyzing the related wholesale operations in a proactive way.

          - Monitor TAP/RAP/NRTRDE files flow from End-to-End perspective with related IT Teams, Roaming Partners & DCH.
          - Prepare daily, weekly and monthly operations reports and traffic analysis.
          - Handle the validation of new IOT implementation and wholesale agreements UAT.
          - Coordinate and handle any updates for the AA.14 document through GSM Association RAEX system.
          - Working with Billing & Finance to ensure IOT tariffs are implemeneted in production for billing and settlement operations.
          - Coordinate any communication between roaming partners and internal departments.
          - Participate in revenue assurance activities to ensure no revenue leakage in roaming daily operations.
          - Support and implement tools for automation of tasks.
          - Develop internal and cross-departmental processes.

  # Education
  education:
    enable: true
    # title: Custom Name
    index: false
    items:
      - title: Bachelor of Science in Computer Engineering
        school:
          name: Arab Academy for Science & Technology AAST, Alexandria Egypt
          url: https://aast.edu/en/
        date: 2006 - 2011
        GPA: 2.8 out of 4.0
        content: |-
          Developed a comprehensive smart home automation system for the graduation project, featuring IP wireless cameras for security and control. Alongside designed integrated circuits to address various abnormal events, including smoke detection, fire detection, and temperature control.
          
          The project was featured in the below exhibitions:
            - Cairo ICT 2011
            - Egyptian Engineering Day 2011

          Extracurricular Activities
            - Volunteer in IEEE - AAST Student Branch (From Feb 2008 - June 2011). During that time i participated in Organizing more than 30 of IEEE events (Startup Weekend Alexandria, CarTronics, Life on a Chip, Mind Mapping, Tech Talks, ESBM 2008, PCB, Robotics Workshop, etc.).
      - title: High School
        school:
          name: El-Nasr Boys School E.B.S, Alexandria Egypt
          url: https://en.wikipedia.org/wiki/El_Nasr_Boys%27_School
        GPA: 93.5% out of 100%
        featuredLink:
          enable: false
          url: https://example.com

  # Courses
<<<<<<< HEAD
  courses:
=======
  courses:
>>>>>>> ea3a0fad1030c2d640b7ef8246735e95c3460438
    enable: true
    # title: Custom Name
    items:
      - title: "4G-LTE EPC: Evolved Packet Core Network | Udemy"
        content: |-
          4G Architecture | 4G Roaming | GTPv2 Protocol | Calls Flows
        url: https://www.udemy.com/certificate/UC-4bd2c4aa-1664-4953-be5d-d3e20d708063/
      - title:  VoLTE | Voice Over LTE & IMS Network | Udemy
        content: |-
          IMS Network Architecture | VoLTE Call Flows | VoLTE Performance Metrics | SIP Protocol
        url: https://www.udemy.com/certificate/UC-1cb5de88-8df6-4690-a51d-c1fac2c5bd1d/
      - title: Mobile CS Voice Core Concepts in 2G GSM, 3G UMTS & 4G-LTE | Udemy
        content: |-
          Voice Call Flows | ISUP Procotol | SIP Protocol
        url: https://www.udemy.com/certificate/UC-c903d203-d233-4566-a44d-52f878e296b0/
      - title: SS7 & SIGTRAN technologies, Architecture & signaling flows | Udemy
        content: |-
          SS7 Protocol Stack | SINGTRAN Protocol Stack
        url: https://www.udemy.com/certificate/UC-5282ef1d-b566-4961-b298-e8a887873979/
      - title: SIP | Session Initiation Protocol in Cellular Networks | Udemy
        content: |-
          SIP Protocol | SIP Diagram | Call Flows
        url: https://www.udemy.com/certificate/UC-0a112f03-23af-45a7-bda9-a6d23c694ec8/
      - title: Qlik Sense for Data Science and Business Intelligence | Udemy
        content: |-
          Business Intelligence | Qlik Sense Dashboards
        url: https://www.udemy.com/certificate/UC-2217c9ef-427a-43ce-9a31-6838a2cb0ddf/
      - title: "Microsoft Excel: Business Intelligence w/ Power Query & DAX | Udemy"
        content: |-
          Data Analytics | Power Query
        url: https://www.udemy.com/certificate/UC-8c720ea3-7fe9-4b94-9309-9535c849bb88/
      - title: Bash Scripting and Shell Programming | Udemy
        content: |-
          Shell Scripts | UNIX Bash
        url: https://www.udemy.com/certificate/UC-c8a25e1a-e1d9-4a06-a387-dbdc55a4344d/
      - title: Agile Development Practices | PMI
        content: |-
          Project Management | Problem Solving      
      - title: CompTIA A+ | CompTIA
        content: |-
          Software Troubleshooting | Security | Virtualization

  # projects
  projects:
    enable: false
    # title: Custom Name
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        #image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - Hugo
          - Bootstrap
          - Javascript
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        #image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - Django
          - Bootstrap
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        #image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - Hugo
          - Bootstrap
          - Javascript
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: Custom Name
    content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
    email: ahmed@shenawy.xyz
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: Enter your email address
    #   messageCaption: Enter your message here

  footer:
    recentPosts:
      path: blogs
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      linkedin: https://www.linkedin.com/in/ahmedshenawy/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: true

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: false
      content: min read
    scrollprogress:
      enable: false

  # For translations
  terms:
    read: Read
    toc: Table Of Contents
    copyright: All rights reserved
    pageNotFound: Page not found
    emailText: Check out this site

  datesFormat:
    article: Jan 2, 2006
    articleList: Jan 2, 2006
    articleRecent: Jan 2, 2006

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type=text/javascript><!-- any script here --></script>
